version: "3.9"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        environment:
            CHOKIDAR_USEPOLLING: "true"
        command: sh -c "npm install --no-save && npm run dev"
        volumes:
            - ./frontend:/app
            - node_modules:/app/node_modules/
        networks:
            - front

    nginx:
        depends_on:
            - frontend
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
        networks:
            - front

networks:
    front:
        driver: bridge

volumes:
    node_modules:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ./frontend/node_modules
